#298 refactor : add StoryListApi
sdp-tech/SASM_BE pull request #316
Opened 2023-03-01 15:04 UTC by kjiyun

StoryListApi refactoring
storycomment 모델 변경 후 migrations 10번째 파일까지 업로드

2023-03-05 00:12 UTC, sejongk requested changes

2023-03-05 00:12 UTC, sejongk commented on stories/views.py
> +            latest=filters.get('latest', True),
이전 story 코드를 보면 최신순 정렬 여부에 대한 파라미터가 'order'로 넘어갔는데 latest로 바꾸신 것으로 보이는데 맞을까요?
맞다면, 바꾸신 이유가 무엇인지, 바꾸고 나서 FE 쪽 코드도 수정이 되었는지 궁금합니다!

2023-03-05 00:12 UTC, sejongk commented on stories/selectors.py
> +                    story_likeuser_set=None,
작성해주신 When의 조건이 **특정 사용자**의 Story 좋아요 여부와 어떻게 관련이 되는지 궁금합니다.

2023-03-13 04:22 UTC, kjiyun commented on stories/selectors.py
> +                    story_likeuser_set=None,
아 이 부분은 제가 착각해서 코드를 잘못짠 것 같습니다. 수정하겠습니다!

2023-03-13 04:24 UTC, kjiyun commented on stories/views.py
> +            latest=filters.get('latest', True),
더 직관적으로 보일 수 있도록 필드값을 수정했습니다. 이에 따라 FE쪽 코드도 수정해서 올려뒀습니다.

2023-03-16 03:55 UTC, sejongk approved these changes
LGTM!! 고생하셨습니다 :)

2023-03-18 05:55 UTC, merged