#298 refactor: add StoryDetailApi
sdp-tech/SASM_BE pull request #319
Opened 2023-03-03 12:42 UTC by kjiyun

story detail

2023-03-16 04:10 UTC, sejongk requested changes

2023-03-16 04:10 UTC, sejongk commented on stories/views.py
> +                story_id=request.query_params.get('id'))
url 패턴을 잘 활용하면 data를 사용할 수 있을 것 같습니다.

2023-03-16 04:10 UTC, sejongk commented on stories/views.py
> +            serializer = MapMarkerSerializer(place)
MapMarkerSerializer를 가져와서 사용하는 대신 다른 API 처럼 해당 class에 선언해서 사용하면 어떨까요?

2023-03-16 04:10 UTC, sejongk commented on stories/views.py
> +    def patch(self, request, story_comment_id):
전송된 모든 필드 값을 받아 업데이트하므로, `patch`가 아니라 `put`이 적절할 것 같고, 반영한다면 FE도 수정되어야할 것 같습니다.

2023-03-16 04:10 UTC, sejongk commented on stories/urls.py
> +     path('comments/', StoryCommentListApi.as_view(), name='story_comments'),
StoryComment의 url 구조는 이렇게 하면 좀 더 직관적이지 않을까 싶은데 어떻게 생각하시는지 궁금합니다.
`/story/<int: story_id>/story_comment/`

2023-03-16 04:11 UTC, sejongk commented
이전 PR과 중복되는 코드가 있어 이전 PR이 반영되고, 충돌이 발생할 경우 해결하고 다시 올려야할 수도 있을 것 같습니다.

2023-03-17 01:01 UTC, yew00n commented on stories/views.py
> -    조회수 중복 방지 - 쿠키 사용
조회수 중복 방지 기능은 불필요해진 건가요?

2023-03-18 12:45 UTC, sejongk commented on stories/views.py
> -    조회수 중복 방지 - 쿠키 사용
넵 일단 조회수 기능은 전반적으로 도입을 보류해야될 것 같습니다.
구현을 위한 기술을 한번 조사하고, 웹/모바일앱 모두 적용한 방안을 찾아봐야할 것 같습니다.

2023-03-19 09:09 UTC, kjiyun commented on stories/views.py
> +                story_id=request.query_params.get('id'))
url에서 story id 값을 받아오는 게 좋을 것 같다는 말씀이신 건가요?

2023-03-19 09:11 UTC, kjiyun commented on stories/views.py
> +            serializer = MapMarkerSerializer(place)
현재 이 기능을 사용하지 않는 것으로 알고 있는데 맞을까요? 기능을 사용하지 않는 것이 확정되면 말씀부탁드립니다!

2023-03-19 09:12 UTC, kjiyun commented on stories/urls.py
> +     path('comments/', StoryCommentListApi.as_view(), name='story_comments'),
좋은 의견인 것 같습니다! 말씀하신 대로 url 구조를 바꾼다면 id값이 story id값이라는 것을 조금 더 직관적으로 알 수 있을 것 같습니다.

2023-03-20 23:06 UTC, sejongk commented on stories/views.py
> +                story_id=request.query_params.get('id'))
넵 맞습니다!

2023-03-20 23:07 UTC, sejongk commented on stories/views.py
> +            serializer = MapMarkerSerializer(place)
넵 FE에 한번 더 문의해서 확정하면 좋을 것 같습니다

2023-03-20 23:11 UTC, sejongk commented on stories/urls.py
> +     path('comments/', StoryCommentListApi.as_view(), name='story_comments'),
커뮤니티 url과의 일관성을 위해 지금처럼 하는 것도 좋을 것 같네요!

2023-03-21 06:11 UTC, closed without merging