Refactor story list
sdp-tech/SASM_BE pull request #348
Opened 2023-04-01 05:14 UTC by kjiyun

- 인기스토리 정렬 방법 추가
- 카테고리 필터 + 내용 검색 기능 추가

2023-04-01 11:38 UTC, sejongk commented on stories/views.py
> +            array=request.query_params.getlist('category', None),
`request.query_params`를 `filters`로 바꿀 순 없을까요?

2023-04-01 11:40 UTC, sejongk commented
지금 프론트와의 인터페이스가 수정된 것으로 보여 프론트쪽도 수정이 필요할 것 같은데, 맞을지 궁금합니다.

2023-04-02 12:01 UTC, yew00n commented on stories/selectors.py
> +<<<<<<< HEAD
collision 흔적 남아있습니당!

2023-05-05 07:05 UTC, kjiyun commented on stories/selectors.py
> +        order_by_time = {'latest' : 'created', 'oldest' : '-created'}
좀 더 가독성이 있게 코드를 짜고 싶어서 따로 나누었었는데 말씀하신 방법도 괜찮을 것 같습니다!

2023-05-05 07:17 UTC, sejongk requested changes

2023-05-05 07:17 UTC, sejongk commented on stories/models.py
> +    # address = models.OneToOneField("places.Place", on_delete=models.CASCADE)
사용되지는 않지만, 일단 주석을 풀고 유지하는 것이 혹시 모를 상황에 대비하기 좋을 것 같습니다.

2023-05-05 07:17 UTC, sejongk commented on stories/selectors.py
> +            for a in array:
nit: `array`와 `a`를 좀 더 명확히 네이밍하는 것이 좋을 것 같습니다.

2023-05-05 07:17 UTC, sejongk commented on stories/urls.py
> +     path('story_detail/create/', StoryCreateApi.as_view(), name='story_create'),
nit: story_detail보다는 stories로 네이밍하는 것이 좋을 것 같습니다.

2023-05-05 07:17 UTC, sejongk commented on stories/views.py
> +            array=request.query_params.getlist('category', None),
음 오류가 발생하는 건 다른 문제가 있는 거 같은데 한번 확인해봅시다

2023-05-05 10:29 UTC, yew00n commented on stories/views.py
> +        writer_sdp_admin = serializers.BooleanField()
writer는 직접 입력 받기보다`request.user` 사용하면 좋을 것 같고, `writer_sdp_admin`는 새로 저장할 필요가 없는 정보이니 안 받아도 될 것 같아요. writer로 가져올 수 있는 정보라서요!

2023-05-10 11:59 UTC, kjiyun commented on stories/selectors.py
> +    def list(search: str = '', order: str = '', array: list = []):
array-> filter 변경하기

2023-05-10 11:59 UTC, kjiyun commented on stories/services.py
> +            place=place,
place 제거

2023-05-10 11:59 UTC, kjiyun commented on stories/views.py
> +        array = serializers.ListField(required=False)
array->filter 변경

2023-05-10 12:30 UTC, sejongk approved these changes

2023-05-10 12:32 UTC, merged