feat: StoryIncludedCuration Api
sdp-tech/SASM_BE pull request #472
Opened 2023-07-20 17:06 UTC by SeoJimin1234

stories/story_included_curation/
StoryIncludedCuration Api

해당 스토리가 포함된 큐레이션의 id, title, photo를 get하는 api

2023-07-21 05:19 UTC, sejongk requested changes
현재 방식에서는 필요한 큐레이션 리스트를 얻기 위해 여러 번의 쿼리가 호출될 것 같은데, Curation.object.~~~에 related_name을 잘 활용하면 쿼리를 하나로 줄일 수 있을 것 같아요.
Hint: `related_name='short_curations'` 를 한번 VSCode에서 검색해보세요

또 지금 각 큐레이션에는 rep_pic하나만 리턴되면 되는데 모든 사진(photos)을 반환하는 것으로 보여요.
앱 FE에 사진이 몇개 필요한지 물어보고 필요한 개수만큼만 반환하도록 변경해주실 수 있나요?

2023-07-22 04:18 UTC, kjiyun approved these changes
LGTM

2023-07-22 04:20 UTC, sejongk requested changes

2023-07-22 04:20 UTC, sejongk commented on stories/selectors.py
> +            rep_pic=Concat(
큐레이션과 연결된 사진이 없을 때 잘 동작하나요??

2023-07-22 04:21 UTC, sejongk commented on stories/selectors.py
> +            rep_pic=Concat(
F('photos__image') 부분이 None이라 의미없는 링크가 만들어질 것 같아서요!

2023-07-24 13:43 UTC, SeoJimin1234 commented on stories/selectors.py
> +            rep_pic=Concat(
확인결과 큐레이션에 사진이 없을 경우 none이 아니라 다른 경로가 만들어져서 수정 후 commit 올렸습니다!

2023-07-25 05:32 UTC, sejongk approved these changes

2023-07-25 05:32 UTC, merged